### ISSUE TITLE
空降cto强制996，公司技术走了90%

### ISSUE THREAD

**Issue by chenwj93** [996icu/996.ICU#18543]

**Comment by smgoon** [comment]
good job

**Comment by cmdit** [comment]
CTO是SB吗？工作是做不完的！技术不行、架构不行，整天加班写BUG吗？写了改，改了写。什么时候是个头。

**Comment by cmdit** [comment]
CTO的职责，是让手底下的人，写出以后少写代码的代码。而不是整天写没意义的代码

**Comment by pangrou** [comment]
> CTO的职责，是让手底下的人，写出以后少写代码的代码。而不是整天写没意义的代码

这个 cto 职责是每天找人谈话&监工，并没有提过任何有价值的技术意见。

**Comment by cmdit** [comment]
这个CTO像是检查院出来的，

在 2019-03-29 10:22:11，"pangrou" <notifications@github.com> 写道：


CTO的职责，是让手底下的人，写出以后少写代码的代码。而不是整天写没意义的代码

这个 cto 职责是每天找人谈话&监工，并没有提过任何有价值的技术意见。

**Comment by pangrou** [comment]
> 这个CTO像是检查院出来的， 在 2019-03-29 10:22:11，"pangrou" <notifications@github.com> 写道： CTO的职责，是让手底下的人，写出以后少写代码的代码。而不是整天写没意义的代码 这个 cto 职责是每天找人谈话&监工，并没有提过任何有价值的技术意见。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

携程出来的呢。一个不懂技术的PMO出身，何德何能来管理技术！

**Comment by cmdit** [comment]
其实很多的公司不懂技术，会导致公司的团队出问题，不懂技术的团队，做CTO，真无语

在 2019-03-29 10:38:10，"pangrou" <notifications@github.com> 写道：


这个CTO像是检查院出来的， 在 2019-03-29 10:22:11，"pangrou" notifications@github.com 写道： CTO的职责，是让手底下的人，写出以后少写代码的代码。而不是整天写没意义的代码 这个 cto 职责是每天找人谈话&监工，并没有提过任何有价值的技术意见。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

携程出来的呢。一个不懂技术的PMO出身，何德何能来管理技术！

**Comment by thatfhrl** [comment]
能力不足以服众的cto

**Comment by cmdit** [comment]
能力不足以服众的cto，会把公司拖垮

在 2019-03-29 10:45:13，"thatfhrl" <notifications@github.com> 写道：


能力不足以服众的cto

**Comment by pangrou** [comment]
> 能力不足以服众的cto，会把公司拖垮 在 2019-03-29 10:45:13，"thatfhrl" <notifications@github.com> 写道： 能力不足以服众的cto — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

所以只剩10%的研发人员了。
然而老板还没有意识到事情的严重性！cto依然稳如狗！
真心感觉技术牛批不如嘴巴牛批，尤其是能把牛批吹进老板心里。

**Comment by chenwj93** [comment]
> 能力不足以服众的cto

基本只会吹名词，要不就是携程如何如何，500人cto群云云

**Comment by cmdit** [comment]
老板说不定还很开心呢！少了这么多人，少了这么多开销。开心~~~

在 2019-03-29 10:53:34，"pangrou" <notifications@github.com> 写道：


能力不足以服众的cto，会把公司拖垮 在 2019-03-29 10:45:13，"thatfhrl" notifications@github.com 写道： 能力不足以服众的cto — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

所以只剩10%的研发人员了。
然而老板还没有意识到事情的严重性！cto依然稳如狗！
真心感觉技术牛批不如嘴巴牛批，尤其是能把牛批吹进老板心里。

**Comment by cmdit** [comment]
只会吹，在携程怎么怎么样！其实那些可能都是别人的成果。现在自己不行了，就会说，手底下的人不行。混到钱，看公司不行了，拍拍屁股走人了，把公司技术团队搞的一塌糊涂。

在 2019-03-29 10:56:45，"windy" <notifications@github.com> 写道：


能力不足以服众的cto

基本只会吹名词，要不就是携程如何如何，500人cto群云云

**Comment by lovears** [comment]
> 板说不定还很开心呢！少了这么多人，少了这么多开销。开心~~~
新招了一批造火箭的来拧螺丝呢

**Comment by cmdit** [comment]
能造火箭的过来拧螺丝，肯定不开心，结果会导致，螺丝都拧不好

在 2019-03-29 11:08:40，"lovears" <notifications@github.com> 写道：


板说不定还很开心呢！少了这么多人，少了这么多开销。开心~~~
新招了一批造火箭的来拧螺丝呢

**Comment by pangrou** [comment]
> 能造火箭的过来拧螺丝，肯定不开心，结果会导致，螺丝都拧不好 在 2019-03-29 11:08:40，"lovears" <notifications@github.com> 写道： 板说不定还很开心呢！少了这么多人，少了这么多开销。开心~~~ 新招了一批造火箭的来拧螺丝呢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

是造火箭的薪资 拧螺丝的水平

**Comment by chenwj93** [comment]
> 能造火箭的过来拧螺丝，肯定不开心，结果会导致，螺丝都拧不好 在 2019-03-29 11:08:40，"lovears" <notifications@github.com> 写道： 板说不定还很开心呢！少了这么多人，少了这么多开销。开心~~~ 新招了一批造火箭的来拧螺丝呢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

哈哈，现在十多个技术，一堆架构师(手动狗头)

**Comment by M2shad0w** [comment]
惊呆了😮
